#!/usr/bin/env python3
"""
Generate QR code PNG files for the printed thesis.

Usage:
  pip install qrcode[pil]
  python generate_qr_codes.py
  python generate_qr_codes.py --base https://YOUR_USERNAME.github.io/thesis_demo

Output:
  qr/*.png
  qr_urls.tex
"""

from __future__ import annotations

import argparse
from pathlib import Path

import qrcode

ROOT = Path(__file__).resolve().parent
QR_DIR = ROOT / "qr"
DOCS = ROOT / "docs"

# (QR stem in LaTeX, HTML file under docs/, margin caption)
# Keep stems (qr_exp3, qr_exp10, …) stable for kap_01.tex; update paths when demos are renamed.
EXPERIMENTS = [
    ("qr_index", "index.html", "All interactive thesis demos."),
    ("qr_exp6", "exp6_cart_split.html",
     r"Slide CART split threshold $t$; watch variance reduction $\Delta$."),
    ("qr_exp1", "exp1_combined.html",
     "Combined RF / MLP / $k$-NN surfaces and maps."),
    ("qr_exp2", "exp2_knn_slider.html",
     "Zoomable comparison maps on a shelf transect."),
    ("qr_exp3", "exp2_knn_slider.html",
     r"Vary $k$; extrapolation zone flattens offshore."),
    ("qr_exp4", "exp4_rf_depth_slider.html",
     r"Tune RF \texttt{max\_depth} on a 2D grid."),
    ("qr_exp4b", "exp4b_rf_trees_slider.html",
     r"Tune RF \texttt{n\_estimators}; smoother patches."),
    ("qr_exp5", "exp4_combined_mlp.html",
     "MLP depth and activation on a 2D map."),
    ("qr_exp7", "exp6_loss_slider.html",
     "MSE vs MAE vs Huber with outliers (1D MLP)."),
    ("qr_exp8", "exp7_activation_slider.html",
     r"ReLU vs tanh vs logistic beyond training support."),
    ("qr_exp9", "exp8_covariate_shift_ptr_ptg.html",
     r"Covariate-shift marginals $p_{\mathrm{tr}}$ vs.\ $p_{\mathrm{tg}}$."),
    ("qr_exp10", "exp9_mlp_training_lab.html",
     r"Toggle BN, dropout, weight decay; neuron activations and TOC loss."),
]

# Legacy filenames still printed in older QR batches — keep redirects in docs/.
LEGACY_REDIRECTS = {
    "exp10_mlp_training_lab.html": "exp9_mlp_training_lab.html",
    "exp9_covariate_shift_ptr_ptg.html": "exp8_covariate_shift_ptr_ptg.html",
    "exp9_mlp_training_lab.html": "exp9_mlp_training_lab.html",  # identity ok
}


def make_qr(url: str, out: Path, box_size: int = 8, border: int = 2) -> None:
    img = qrcode.make(url, box_size=box_size, border=border)
    out.parent.mkdir(parents=True, exist_ok=True)
    img.save(out)
    print(out)


def write_latex_url_map(base: str, out: Path) -> None:
    lines = [
        "% Auto-generated by generate_qr_codes.py — do not edit by hand.",
        "% Regenerate: python generate_qr_codes.py --base <GitHub Pages URL>",
        "\\makeatletter",
        "\\providecommand{\\DemoQrPrintUrl}[1]{%",
        "  \\@ifundefined{DemoQrPrintUrl@#1}{%",
        f"    \\url{{{base}/}}%",
        "  }{%",
        "    \\csname DemoQrPrintUrl@#1\\endcsname",
        "  }%",
        "}",
        "\\providecommand{\\DemoQrPrintDesc}[1]{%",
        "  \\@ifundefined{DemoQrPrintDesc@#1}{}{%",
        "    \\csname DemoQrPrintDesc@#1\\endcsname",
        "  }%",
        "}",
    ]
    for stem, path, desc in EXPERIMENTS:
        url = base if not path else f"{base}/{path}"
        lines.append(f"\\@namedef{{DemoQrPrintUrl@{stem}}}{{\\url{{{url}}}}}")
        lines.append(f"\\@namedef{{DemoQrPrintDesc@{stem}}}{{{desc}}}")
    lines.append("\\makeatother")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(out)


def write_legacy_redirects() -> None:
    """Auto-redirect old demo URLs so previously printed QRs still work."""
    template = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="refresh" content="0; url={target}"/>
  <title>Redirecting…</title>
</head>
<body>
  <p>This demo moved to <a href="{target}">{target}</a>.</p>
</body>
</html>
"""
    for old_name, new_name in LEGACY_REDIRECTS.items():
        if old_name == new_name:
            continue
        out = DOCS / old_name
        if out.exists() and "Redirecting" not in out.read_text(encoding="utf-8", errors="ignore")[:200]:
            # Do not overwrite real demos that happen to share a legacy name.
            continue
        out.write_text(template.format(target=new_name), encoding="utf-8")
        print("redirect", out.name, "->", new_name)


def validate_targets() -> None:
    missing = [p for _, p, _ in EXPERIMENTS if p and not (DOCS / p).exists()]
    if missing:
        raise FileNotFoundError(
            "Missing demo HTML under docs/:\n  "
            + "\n  ".join(missing)
            + "\nRun: python build_experiments.py"
        )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--base",
        default="https://paramnav.github.io/thesis_demo",
        help="GitHub Pages base URL (no trailing slash)",
    )
    args = parser.parse_args()
    base = args.base.rstrip("/")

    validate_targets()
    write_legacy_redirects()

    for stem, path, _desc in EXPERIMENTS:
        url = base if not path else f"{base}/{path}"
        make_qr(url, QR_DIR / f"{stem}.png")

    write_latex_url_map(base, ROOT / "qr_urls.tex")

    print(f"\nWrote {len(EXPERIMENTS)} QR codes to {QR_DIR}/")
    print("Recompile diss.tex after updating.")


if __name__ == "__main__":
    main()
