#!/usr/bin/env python3
"""
Generate QR code PNG files for the printed thesis.

Usage:
  pip install qrcode[pil]
  python generate_qr_codes.py
  python generate_qr_codes.py --base https://YOUR_USERNAME.github.io/thesis_demo

Output:
  qr/*.png
  qr_urls.tex
"""

from __future__ import annotations

import argparse
from pathlib import Path

import qrcode
from qrcode.constants import ERROR_CORRECT_H

from demo_urls import EXP1, EXP2, EXP3, EXP4, EXP5, EXP6, LEGACY_REDIRECTS

ROOT = Path(__file__).resolve().parent
QR_DIR = ROOT / "qr"
DOCS = ROOT / "docs"

# (QR stem in LaTeX, HTML file under docs/, margin caption)
EXPERIMENTS = [
    ("qr_exp1", EXP1,
     r"Experiment 1 — slide CART split threshold $t$; watch variance reduction $\Delta$."),
    ("qr_exp2", EXP2,
     r"Experiment 2 — RF shelf transect; toggle to 1D extrapolation."),
    ("qr_exp3", EXP3,
     r"Experiment 3 — $k$-NN shelf transect; toggle to 1D extrapolation."),
    ("qr_exp4", EXP4,
     r"Experiment 4 — MLP shelf transect; toggle to 1D extrapolation."),
    ("qr_exp5", EXP5,
     r"Experiment 5 — information gain map; toggle to $\sigma_{\mathrm{ref}}$ pedagogy."),
    ("qr_exp6", EXP6,
     r"Experiment 6 — spatial Shapley maps: $\phi_1$, $\phi_2$, and Eq.~\ref{eq:shapdecomp}."),
]


def make_qr(url: str, out: Path, box_size: int = 10, border: int = 2) -> None:
    qr = qrcode.QRCode(error_correction=ERROR_CORRECT_H, box_size=box_size, border=border)
    qr.add_data(url)
    qr.make(fit=True)
    out.parent.mkdir(parents=True, exist_ok=True)
    qr.make_image().save(out)
    print(out)


def write_latex_url_map(base: str, out: Path) -> None:
    lines = [
        "% Auto-generated by generate_qr_codes.py — do not edit by hand.",
        "% Regenerate: python generate_qr_codes.py --base <GitHub Pages URL>",
        "\\makeatletter",
        "\\providecommand{\\DemoQrPrintUrl}[1]{%",
        "  \\@ifundefined{DemoQrPrintUrl@#1}{%",
        f"    \\url{{{base}/}}%",
        "  }{%",
        "    \\csname DemoQrPrintUrl@#1\\endcsname",
        "  }%",
        "}",
        "\\providecommand{\\DemoQrPrintDesc}[1]{%",
        "  \\@ifundefined{DemoQrPrintDesc@#1}{}{%",
        "    \\csname DemoQrPrintDesc@#1\\endcsname",
        "  }%",
        "}",
    ]
    for stem, path, desc in EXPERIMENTS:
        url = base if not path else f"{base}/{path}"
        lines.append(f"\\@namedef{{DemoQrPrintUrl@{stem}}}{{\\url{{{url}}}}}")
        lines.append(f"\\@namedef{{DemoQrPrintDesc@{stem}}}{{{desc}}}")
    lines.append("\\makeatother")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(out)


def write_legacy_redirects() -> None:
    """Auto-redirect old demo URLs so previously printed QRs still work."""
    template = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="refresh" content="0; url={target}"/>
  <title>Redirecting…</title>
</head>
<body>
  <p>This demo moved to <a href="{target}">{target}</a>.</p>
</body>
</html>
"""
    for old_name, new_name in LEGACY_REDIRECTS.items():
        if old_name == new_name:
            continue
        out = DOCS / old_name
        out.write_text(template.format(target=new_name), encoding="utf-8")
        print("redirect", out.name, "->", new_name)


def validate_targets() -> None:
    missing = [p for _, p, _ in EXPERIMENTS if p and not (DOCS / p).exists()]
    if missing:
        raise FileNotFoundError(
            "Missing demo HTML under docs/:\n  "
            + "\n  ".join(missing)
            + "\nRun: python build_experiments.py"
        )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--base",
        default="https://paramnav.github.io/thesis_demo",
        help="GitHub Pages base URL (no trailing slash)",
    )
    args = parser.parse_args()
    base = args.base.rstrip("/")

    validate_targets()
    write_legacy_redirects()

    for stem, path, _desc in EXPERIMENTS:
        url = base if not path else f"{base}/{path}"
        make_qr(url, QR_DIR / f"{stem}.png")

    write_latex_url_map(base, ROOT / "qr_urls.tex")

    print(f"\nWrote {len(EXPERIMENTS)} QR codes to {QR_DIR}/")
    print("Recompile diss.tex after updating.")


if __name__ == "__main__":
    main()
