#!/usr/bin/env python3
"""
Generate QR code PNG files for the printed thesis.

Usage:
  pip install qrcode[pil]
  python generate_qr_codes.py
  python generate_qr_codes.py --base https://YOUR_USERNAME.github.io/thesis_demo

Output:
  qr/*.png
  qr_urls.tex
"""

from __future__ import annotations

import argparse
from pathlib import Path

import qrcode
from qrcode.constants import ERROR_CORRECT_H

ROOT = Path(__file__).resolve().parent
QR_DIR = ROOT / "qr"
DOCS = ROOT / "docs"

# (QR stem in LaTeX, HTML file under docs/, margin caption)
EXPERIMENTS = [
    ("qr_exp6", "exp6_cart_split.html",
     r"Slide CART split threshold $t$; watch variance reduction $\Delta$."),
    ("qr_exp1a_rf", "exp1a_rf.html",
     r"Experiment 1a — RF shelf transect; toggle to 1D extrapolation."),
    ("qr_exp1a_knn", "exp1a_knn.html",
     r"Experiment 1b — $k$-NN shelf transect; toggle to 1D extrapolation."),
    ("qr_exp1a_mlp", "exp1a_mlp.html",
     r"Experiment 1c — MLP shelf transect; toggle to 1D extrapolation."),
    ("qr_exp_ig", "exp5_information_gain.html",
     r"Information gain map (Exp.~5); toggle to $\sigma_{\mathrm{ref}}$ pedagogy (Exp.~11)."),
    ("qr_exp12_shap", "exp12_shapley_values.html",
     r"2-feature Shapley toy: coalitions, $\phi_i$, and $f(x)=\mathbb{E}[f]+\sum_i\phi_i$ (Eq.~\ref{eq:shapdecomp})."),
]

LEGACY_REDIRECTS = {
    "exp10_mlp_training_lab.html": "index.html",
    "exp9_covariate_shift_ptr_ptg.html": "index.html",
    "exp8_covariate_shift_ptr_ptg.html": "index.html",
    "exp9_mlp_training_lab.html": "index.html",
    "exp10_multi_task_learning.html": "index.html",
    "exp12_information_gain_pedagogy.html": "exp5_information_gain.html",
    "exp2_knn_slider.html": "exp2_knn.html",
    "exp1_combined.html": "exp1a_rf.html",
    "exp1a_combined.html": "exp1a_rf.html",
    "exp3_combined_rf.html": "exp1a_rf.html",
}


def make_qr(url: str, out: Path, box_size: int = 10, border: int = 2) -> None:
    qr = qrcode.QRCode(error_correction=ERROR_CORRECT_H, box_size=box_size, border=border)
    qr.add_data(url)
    qr.make(fit=True)
    out.parent.mkdir(parents=True, exist_ok=True)
    qr.make_image().save(out)
    print(out)


def write_latex_url_map(base: str, out: Path) -> None:
    lines = [
        "% Auto-generated by generate_qr_codes.py — do not edit by hand.",
        "% Regenerate: python generate_qr_codes.py --base <GitHub Pages URL>",
        "\\makeatletter",
        "\\providecommand{\\DemoQrPrintUrl}[1]{%",
        "  \\@ifundefined{DemoQrPrintUrl@#1}{%",
        f"    \\url{{{base}/}}%",
        "  }{%",
        "    \\csname DemoQrPrintUrl@#1\\endcsname",
        "  }%",
        "}",
        "\\providecommand{\\DemoQrPrintDesc}[1]{%",
        "  \\@ifundefined{DemoQrPrintDesc@#1}{}{%",
        "    \\csname DemoQrPrintDesc@#1\\endcsname",
        "  }%",
        "}",
    ]
    for stem, path, desc in EXPERIMENTS:
        url = base if not path else f"{base}/{path}"
        lines.append(f"\\@namedef{{DemoQrPrintUrl@{stem}}}{{\\url{{{url}}}}}")
        lines.append(f"\\@namedef{{DemoQrPrintDesc@{stem}}}{{{desc}}}")
    lines.append("\\makeatother")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(out)


def write_legacy_redirects() -> None:
    """Auto-redirect old demo URLs so previously printed QRs still work."""
    template = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="refresh" content="0; url={target}"/>
  <title>Redirecting…</title>
</head>
<body>
  <p>This demo moved to <a href="{target}">{target}</a>.</p>
</body>
</html>
"""
    for old_name, new_name in LEGACY_REDIRECTS.items():
        if old_name == new_name:
            continue
        out = DOCS / old_name
        if out.exists() and "Redirecting" not in out.read_text(encoding="utf-8", errors="ignore")[:200]:
            continue
        out.write_text(template.format(target=new_name), encoding="utf-8")
        print("redirect", out.name, "->", new_name)


def validate_targets() -> None:
    missing = [p for _, p, _ in EXPERIMENTS if p and not (DOCS / p).exists()]
    if missing:
        raise FileNotFoundError(
            "Missing demo HTML under docs/:\n  "
            + "\n  ".join(missing)
            + "\nRun: python build_experiments.py"
        )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--base",
        default="https://paramnav.github.io/thesis_demo",
        help="GitHub Pages base URL (no trailing slash)",
    )
    args = parser.parse_args()
    base = args.base.rstrip("/")

    validate_targets()
    write_legacy_redirects()

    for stem, path, _desc in EXPERIMENTS:
        url = base if not path else f"{base}/{path}"
        make_qr(url, QR_DIR / f"{stem}.png")

    write_latex_url_map(base, ROOT / "qr_urls.tex")

    print(f"\nWrote {len(EXPERIMENTS)} QR codes to {QR_DIR}/")
    print("Recompile diss.tex after updating.")


if __name__ == "__main__":
    main()
